### ISSUE TITLE
Flash example does not specify version

### ISSUE THREAD

**Issue by syst0m** [mobolic/facebook-sdk#365]
### Version of the SDK being used
Installed on Ubuntu 17.04 with:
```
virtualenv facebookenv
source facebookenv/bin/activate
pip install facebook-sdk
```

### Expected Behavior
Sign in on: http://0.0.0.0:8000/

### Actual Behavior
```
h {message: "invalid version specified", innerError: undefined}innerError: undefinedmessage: "invalid version specified"__proto__: Error
    at Object.a (https://connect.facebook.net/en_US/sdk.js:62:151)
    at require (https://connect.facebook.net/en_US/sdk.js:24:629)
    at require (https://connect.facebook.net/en_US/sdk.js:24:591)
    at require (https://connect.facebook.net/en_US/sdk.js:24:591)
    at require (https://connect.facebook.net/en_US/sdk.js:24:591)
    at require (https://connect.facebook.net/en_US/sdk.js:24:591)
    at require (https://connect.facebook.net/en_US/sdk.js:24:591)
    at require (https://connect.facebook.net/en_US/sdk.js:24:591)
    at __d (https://connect.facebook.net/en_US/sdk.js:24:783)
    at Object.<anonymous> (https://connect.facebook.net/en_US/sdk.js:73:1)
(anonymous) @ sdk.js:109
```

### Steps to Reproduce
Open in Google Chrome Version 58.0.3029.96 (64-bit)

**Comment by syst0m** [comment]
Changed sdk.js->all.js.
Sign in works now.

/```
/ Load the SDK Asynchronously
        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
```

**Comment by martey** [comment]
Are you using one of facebook-sdk's examples and getting this error? If so, which one?

**Comment by srichakradhar** [comment]
facing the same issue on chrome, firefox, safari..
```
Uncaught h {message: "invalid version specified", innerError: undefined}innerError: undefinedmessage: "invalid version specified"__proto__: Error
    at Object.a (https://connect.facebook.net/en_US/sdk.js:63:150)
    at require (https://connect.facebook.net/en_US/sdk.js:24:627)
    at require (https://connect.facebook.net/en_US/sdk.js:24:590)
    at require (https://connect.facebook.net/en_US/sdk.js:24:590)
    at require (https://connect.facebook.net/en_US/sdk.js:24:590)
    at require (https://connect.facebook.net/en_US/sdk.js:24:590)
    at require (https://connect.facebook.net/en_US/sdk.js:24:590)
    at require (https://connect.facebook.net/en_US/sdk.js:24:590)
    at __d (https://connect.facebook.net/en_US/sdk.js:24:780)
    at Object.<anonymous> (https://connect.facebook.net/en_US/sdk.js:74:1)
(anonymous) @ sdk.js:110
setTimeout (async)
t.__wrapper @ sdk.js:110
(anonymous) @ sdk.js:159
setTimeout (async)
_sdkBound @ sdk.js:22
a @ sdk.js:159
require @ sdk.js:24
require @ sdk.js:24
__d @ sdk.js:24
(anonymous) @ sdk.js:160
(anonymous) @ sdk.js:187
(anonymous) @ sdk.js:187
```
